# ベースイメージ
FROM python:3

# 作業ディレクトリの設定
WORKDIR /app

# 依存関係のインストール
COPY requirements-dev.txt /app/
RUN pip install -r requirements-dev.txt

# アプリケーションのコピー
COPY . /app

# ポートの露出
EXPOSE 8000

# Django サーバーの起動
CMD ["python", "manage.py", "runserver", "127.0.0.1"]
