version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
  
  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
    - ./frontend/build:/usr/share/nginx/html
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/proxy_params:/etc/nginx/proxy_params
    - static_volume:/usr/share/nginx/html/static
    depends_on:
      - web

volumes:
  static_volume: {}
