version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: /app/entrypoint.dev.sh

  postgres:
    container_name: postgres
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/lib/postgresql/data/db_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-db.sh:/usr/local/bin/init-db.sh
    platform: linux/x86_64
    entrypoint: /usr/local/bin/init-db.sh
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
