# Base image
FROM python:3

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements-dev.txt /app/
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy the application
COPY . /app
RUN chmod -R 755 /app

# Copy entrypoint script into the image
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
