# ベースイメージ
FROM python:3

# 作業ディレクトリの設定
WORKDIR /app

# 依存関係のインストール
COPY requirements-dev.txt /app/
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# アプリケーションのコピー
COPY . /app

RUN python manage.py migrate

# Gunicorn の設定
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "loginProject.wsgi:application"]
CMD ["python", "manage.py","runserver","0.0.0.0:8000"]