version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command:
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
