AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EC2 and RDS instances with associated security groups and Elastic IP.

Resources:
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: Retain
    Properties:
      GroupDescription: 'Security group for EC2 instance'
      VpcId: 'vpc-0277fe13aac9a146d'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: 'tcp'
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0'
        - IpProtocol: 'tcp'
          FromPort: 80
          ToPort: 80
          CidrIp: '220.220.239.102/32'
      SecurityGroupEgress:
        - IpProtocol: 'tcp'
          FromPort: 0
          ToPort: 65535
          CidrIp: '0.0.0.0/0'
  RDSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: Retain
    Properties:
      GroupDescription: 'Security group for RDS instance'
      VpcId: 'vpc-0277fe13aac9a146d'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId:
            Ref: 'EC2SecurityGroup'
  EC2RDSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: Retain
    Properties:
      GroupDescription: 'Security group to securely connect to RDS'
      VpcId: 'vpc-0277fe13aac9a146d'
      SecurityGroupEgress:
        - IpProtocol: 'tcp'
          FromPort: 5432
          ToPort: 5432
          DestinationSecurityGroupId:
            Ref: 'RDSSecurityGroup'
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    DeletionPolicy: Retain
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09a81b370b76de6a2 # Ubuntu Server 22.04 LTS AMI
      KeyName: ai-reversi
      SubnetId: subnet-00f244f854eae69f4
      SecurityGroupIds:
        - sg-02de48bd82e689962 # Security group for EC2 instance
      Tags:
        - Key: Name
          Value: ai-reversi

  ElasticIP:
    Type: 'AWS::EC2::EIP'
    DeletionPolicy: Retain
    Properties:
      Domain: vpc
      InstanceId: !Ref EC2Instance

  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    DeletionPolicy: Retain
    Properties:
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20 # Adjust the storage size as needed
      Engine: postgres
      EngineVersion: '15.4' # Specify the version you are using
      DBInstanceIdentifier: ai-reversi-postgre
      MasterUsername: db_rds_admin # Change to your master username
      MasterUserPassword: 'your_master_password' # Set your master password
      DBSubnetGroupName: rds-ec2-db-subnet-group-1
      VPCSecurityGroups:
        - sg-0c3b0ebbe15063d05 # Security group for RDS
      Tags:
        - Key: Name
          Value: ai-reversi-postgre


