AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EC2 and RDS instances with associated security groups and Elastic IP.

Resources:

  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for EC2 instance'
      VpcId: 'vpc-0277fe13aac9a146d'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0' # Adjust as necessary for your security
        - IpProtocol: 'tcp'
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0' # Adjust as necessary for your security
        - IpProtocol: 'tcp'
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0' # Adjust as necessary for your security

  RDSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for RDS instance'
      VpcId: 'vpc-0277fe13aac9a146d'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EC2SecurityGroup

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09a81b370b76de6a2 # Ubuntu Server 22.04 LTS AMI
      KeyName: ai-reversi
      SubnetId: subnet-00f244f854eae69f4
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: ai-reversi

  # The existing Elastic IP will be added manually later
  #ElasticIP:
  #  Type: 'AWS::EC2::EIP'
  #  Properties:
  #    Domain: vpc
  #    InstanceId: !Ref EC2Instance

  RDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ai-reversi-db-secret
      Description: "Secret for AI Reversi RDS database"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "db_rds_admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"

  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 10 # Adjust as needed
      Engine: postgres
      EngineVersion: '15.4' # Update to the version you want to use
      DBInstanceIdentifier: ai-reversi-postgre
      MasterUsername: db_rds_admin
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RDSSecret}:SecretString:password}}'
      DBSubnetGroupName: rds-ec2-db-subnet-group-1
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      Tags:
        - Key: Name
          Value: ai-reversi-postgre
        
Outputs:
  RDSSecretARN:
    Description: "Secret ARN for RDS instance"
    Value: !Ref RDSSecret
