# Generated by Django 4.2.7 on 2023-11-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_username',
            field=models.CharField(default='username', max_length=255),
        ),
    ]
